version: '3.4'

services:
  marketplace.api:
    container_name: marketplace.api
    environment:
      - ASPNETCORE_ENVIRONMENT=UAT
      - ConnectionStrings__SqlServerConnectionString=Server=mssql;Database=Marketplace;Persist Security Info=True;UID=sa;Password=QaAER#$12#!#!@#Fsfdf;MultipleActiveResultSets=True;TrustServerCertificate=True
      - ConnectionStrings__EventStoreConnectionString=esdb://eventstore:2113?tls=false&tlsVerifyCert=false
      - ConnectionStrings__RedisConnectionString=redis:6379
      - RavenDB__Url=http://ravendb:8080
      - RavenDB__Database=Marketplace
      - ServiceSettings__PersistenceApproach=EntityFramework
      - ServiceSettings__StreamingApproach=EventStore
    ports:
      - "5886:8080"

  ravendb:
    container_name: ravendb
    ports:
      - "8080:8080"
    environment:
      - RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork
      - RAVEN_ARGS="--Setup.Mode=None"
    volumes:
      - ravendb_data:/var/lib/ravendb/data
      - ravendb_etc:/etc/ravendb

  mssql:
    container_name: mssql
    environment:
      - SA_PASSWORD=QaAER#$12#!#!@#Fsfdf
      - ACCEPT_EULA=Y
    restart: always
    ports:
      - "11433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql/data

  eventstore:
    container_name: eventstore
    ports:
      - "21131:2113"
      - "11131:1113"
    environment:
       - EVENTSTORE_CLUSTER_SIZE=1
       - EVENTSTORE_RUN_PROJECTIONS=All
       - EVENTSTORE_START_STANDARD_PROJECTIONS=true
       - EVENTSTORE_HTTP_PORT=2113
       - EVENTSTORE_INSECURE=true
       - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    volumes:
      - eventstore_lib:/var/lib/eventstore
      - eventstore_log:/var/log/eventstore

  redis:
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:    
    container_name: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example  