version: '3.4'

services:
  marketplace.api:
    image: ${DOCKER_REGISTRY-}marketplace
    build:
      context: ../../.
      dockerfile: 02-Marketplace/05-Edge/Marketplace.Api/Dockerfile

  ravendb:
    image: ravendb/ravendb:6.0.2-ubuntu.22.04-x64

  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest

  redis:
    image: redis:alpine3.19
  
  broker:
    image: confluentinc/cp-kafka:7.5.3

  schema-registry:
    image: confluentinc/cp-schema-registry:7.5.3

  connect:
    image: cnfldemos/cp-server-connect-datagen:0.6.2-7.5.0

  control-center:
    image: confluentinc/cp-enterprise-control-center:7.5.3

  ksqldb-server:
    image: confluentinc/cp-ksqldb-server:7.5.3

  ksqldb-cli:
    image: confluentinc/cp-ksqldb-cli:7.5.3

  ksql-datagen:
    image: confluentinc/ksqldb-examples:7.5.3

  rest-proxy:
    image: confluentinc/cp-kafka-rest:7.5.3

  postgres:
    image: postgres:12.19

volumes:
  sqlserver_data:
  ravendb_data:
  ravendb_etc:
  eventstore_lib:
  eventstore_log:
  redis_data:
  kafka_broker_secrets:
  kafka_broker_data:
  kafka_schema_registry_secrets:
  kafka_connect_jars:
  kafka_connect_secrets:
  kafka_connect_kafkasecrets:
  kafka_connect_data:
  postgres_data:  