version: '3.4'

services:
  marketplace:
    image: ${DOCKER_REGISTRY-}marketplace
    build:
      context: .
      dockerfile: 04-EndPoints/Marketplace/Dockerfile

  ravendb:
    image: ravendb/ravendb:ubuntu-latest

  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest

  eventstore:
    image: eventstore/eventstore:21.10.0-buster-slim

volumes:
  sqlserver_data:
  ravendb_data:
  ravendb_etc:
  eventstore_lib:
  eventstore_log: