version: '3.4'

services:
  marketplace:
    container_name: marketplace
    environment:
      - ASPNETCORE_ENVIRONMENT=UAT
    ports:
      - "80"

  ravendb:
    container_name: ravendb
    ports:
      - "8080:8080"
    environment:
      - RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork
      - RAVEN_ARGS="--Setup.Mode=None"
    volumes:
      - ravendb_data:/var/lib/ravendb/data
      - ravendb_etc:/etc/ravendb

  mssql:
    container_name: mssql
    environment:
      - SA_PASSWORD=QaAER#$12#!#!@#Fsfdf
      - ACCEPT_EULA=Y
    restart: always
    ports:
      - "11433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql/data

  eventstore:
    container_name: eventstore
    ports:
      - "21131:2113"
      - "11131:1113"
    environment:
       - EVENTSTORE_CLUSTER_SIZE=1
       - EVENTSTORE_RUN_PROJECTIONS=All
       - EVENTSTORE_START_STANDARD_PROJECTIONS=true
       - EVENTSTORE_EXT_TCP_PORT=1113
       - EVENTSTORE_HTTP_PORT=2113
       - EVENTSTORE_INSECURE=true
       - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
       - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    volumes:
      - eventstore_lib:/var/lib/eventstore
      - eventstore_log:/var/log/eventstore