version: '3.4'

services:
  marketplace:
    container_name: marketplace
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  ravendb:
    container_name: ravendb
    ports:
      - "8080:8080"
    environment:
      - RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork
      - RAVEN_ARGS="--Setup.Mode=None"
    volumes:
      - ravendb_data:/var/lib/ravendb/data
      - ravendb_etc:/etc/ravendb

  mssql:
    container_name: mssql
    environment:
      - SA_PASSWORD=QaAER#$12#!#!@#Fsfdf
      - ACCEPT_EULA=Y
    restart: always
    ports:
      - "11433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql/data

  eventstore:
    container_name: eventstore
    ports:
        - "12113:2113"
        - "11113:1113"
    environment:
        - EVENTSTORE_CLUSTER_SIZE=1
        - EVENTSTORE_RUN_PROJECTIONS=All
        - EVENTSTORE_START_STANDARD_PROJECTIONS=True
        - EVENTSTORE_DB=/var/lib/eventstore
        - EVENTSTORE_INDEX=/var/lib/eventstore-index
        - EVENTSTORE_LOG=/var/log/eventstore
        - EVENTSTORE_EXT_TCP_PORT=11113
        - EVENTSTORE_EXT_HTTP_PORT=12113
    volumes:
      - eventstore_lib:/var/lib/eventstore
      - eventstore_index:/var/lib/eventstore-index
      - eventstore_log:/var/log/eventstore