version: '3.4'

services:
  marketplace:
    container_name: marketplace
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  ravendb:
    container_name: ravendb
    ports:
      - "8080:8080"
    environment:
      - RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork
      - RAVEN_ARGS="--Setup.Mode=None"
    volumes:
      - ravendb_data:/var/lib/ravendb/data
      - ravendb_etc:/etc/ravendb

  mssql:
    container_name: mssql
    environment:
      - SA_PASSWORD=QaAER#$12#!#!@#Fsfdf
      - ACCEPT_EULA=Y
    restart: always
    ports:
      - "11433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql/data

  eventstore:
    container_name: eventstore
    ports:
        - "12113:2113"
        - "11113:1113"
    volumes:
      - eventstore_lib:/var/lib/eventstore
      - eventstore_log:/var/log/eventstore 